### ISSUE TITLE
Code license?

### ISSUE THREAD

**Issue by leahch** [gsingh93/display-manager#2]
Hello Gulshan.
I simply rewrite your code. I added initialization user variables with changed user uid/gid to pam.c, added monitor process and simple configuration file. I also have to add licence to my project which correspond your code licence. Please remind me your code license.
My project is here - https://github.com/leahch/display-manager

**Comment by gsingh93** [comment]
I forgot to add a license to the repo, but it's MIT. I'll officially add one later, thanks for checking with me.

**Comment by gsingh93** [comment]
Done.
